rly_file = "Western_Lyon_Tram_Train.rly"
ttb_files = [ "Lyon_Tram_Train_Jan_2026.ttb",]
img_files = [ "Western_Lyon_Tram_Train.bmp",]
doc_files = [ "README.md",]
release_date = "2026-01-07"
version = "1.0.0"
country_code = "FR"
factual = true
description = ""
year = 2026
display_name = "Western Lyon Tram Train"
name = "Western Lyon Tram Train"
signal_position = "left"
author = "Kristian ZarÄ™bski"
contributors = []
ssn_files = [ "Western_Lyon_Tram_Train_0530_Jan_2026.ssn",]
